# version: "3"
# services:
#   zookeeper:
#     #image: 'bitnami/zookeeper:latest'
#     image: wurstmeister/zookeeper
#     ports:
#       - '2181:2181'
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     #image: 'bitnami/kafka:latest'
#     image: wurstmeister/kafka
#     container_name: 'kafka'
#     ports:
#       - '9092:9092'
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_OFFSETS_TOPICS_REPLICATION_FACTOR=1 confluentinc/cp-kafka
#     depends_on:
#       - zookeeper

version: '3'

services:
  zookeeper: 
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports: 
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    
    
    
